apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-2
spec:
  parallelism: 2
  template:
    metadata:
      name: job-wq-2
    spec:
      containers:
      - name: c
        image: job-wq-2
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
