apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-3
spec:
  parallelism: 2
  template:
    metadata:
      name: job-wq-3
    spec:
      containers:
      - name: c
        image: job-wq-3
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
